// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALp-Yuh4hiXusVLW4RVgdjIlpT9fO-2fc',
    appId: '1:924500614865:web:1643d6f46af45717ee2ff0',
    messagingSenderId: '924500614865',
    projectId: 'shopfy-c102b',
    authDomain: 'shopfy-c102b.firebaseapp.com',
    storageBucket: 'shopfy-c102b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlGVCJpkHYLXt-I-Q2Tokbto8gaP3hMcg',
    appId: '1:924500614865:android:5fa3654966f149a9ee2ff0',
    messagingSenderId: '924500614865',
    projectId: 'shopfy-c102b',
    storageBucket: 'shopfy-c102b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKLuMTspEQELRUmA0X95KzcDHSMtSnRZM',
    appId: '1:924500614865:ios:730187296b824a8cee2ff0',
    messagingSenderId: '924500614865',
    projectId: 'shopfy-c102b',
    storageBucket: 'shopfy-c102b.appspot.com',
    iosBundleId: 'com.example.shopfy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKLuMTspEQELRUmA0X95KzcDHSMtSnRZM',
    appId: '1:924500614865:ios:ce9bf514e0652ed4ee2ff0',
    messagingSenderId: '924500614865',
    projectId: 'shopfy-c102b',
    storageBucket: 'shopfy-c102b.appspot.com',
    iosBundleId: 'com.example.shopfy.RunnerTests',
  );
}
